name: Sonar Scanner

inputs:
  projectName:
    description: Nome do projeto no Sonarqube
    required: true
  projectKey:
    description: GroupId projetos Java e Name demais projetos
    required: true
  appVersion:
    description: Versão da aplicação
    required: false
  url:
    description: URL para publicação do resultado de Scan
    required: true
  token:
    description: Token de Acesso ao Sonarqube
    required: true
outputs:
  time:
    description: Horário em timestamp. Testando Outputs

runs:
  using: node20
  main: dist/index.js
